### PR TITLE
Update ontologies_wg.md

### PR DESCRIPTION
**Pull request by PietroLiuzzo**

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
I have converted from html to md using https://products.aspose.app/html/conversion/zip-to-md/download
I think I need to upload the images

**Comment by petrifiedvoices** [comment]
all looking good

**Comment by PietroLiuzzo** [comment]
mmm... not sure... the images are missing, isn't it?

**Comment by petrifiedvoices** [comment]
Do you prefer to have the EpOnt document on a new page? It's not a problem - but we can discuss it later as we go.

This should work for images: 
The image has to exist locally / on GitHub in the folder `assets`
Provide a description of your XXX image

**Pull request merged**
